# Makefile for building SDL3 (MorphOS)
#
# Features enabled in this build:
#   - Pthreads
#   - Unix timer backend
#   - AHI audio backend
#   - OpenGL video + OpenGL renderer
#   - Gamepad support: sensors library / hotplug supported
#   - Dialog support (MorphOS backend)
#   - AltiVec optimizations (selected files)
#	- Multi-monitor supported
#	- Software and OpenGL renderers supported
#
# Notes:
#   - "debug" adds -D__SDL_DEBUG
#   - "install" copies headers and static libs to /gg/usr/local
#
# Known issues:
#   - MessageBox: no window parent support
#   - testcolorspace: incorrect color readback with OpenGL renderer

AR = ppc-morphos-ar
RANLIB = ppc-morphos-ranlib
CC = ppc-morphos-gcc-11
CXX = ppc-morphos-g++-11
STRIP = ppc-morphos-strip

AMIGADATE = $(shell date +"%-d.%m.%Y")

DEFINES =  -DAROS_ALMOST_COMPATIBLE -D__AMIGADATE__=\"$(AMIGADATE)\"
CFLAGS  =  -noixemul -O2 -Wall -ffast-math -Wshadow -fcommon -I./include -I./include/build_config -I./include/SDL3 -I./src $(DEFINES)

TARGET_STATIC  = libSDL3.a
TESTLIB_STATIC = libSDL3_test.a

SOURCES = \
	$(wildcard ./src/*.c) \
	$(wildcard ./src/atomic/*.c) \
	$(wildcard ./src/audio/*.c) \
	$(wildcard ./src/audio/ahi/*.c) \
	$(wildcard ./src/audio/dummy/*.c) \
	$(wildcard ./src/camera/*.c) \
	$(wildcard ./src/cpuinfo/*.c) \
	$(wildcard ./src/dialog/*.c) \
	$(wildcard ./src/dialog/morphos/*.c) \
	$(wildcard ./src/events/*.c) \
	./src/filesystem/SDL_filesystem.c \
	$(wildcard ./src/filesystem/posix/*.c) \
	$(wildcard ./src/filesystem/morphos/*.c) \
	./src/gpu/SDL_gpu.c \
	$(wildcard ./src/haptic/*.c) \
	$(wildcard ./src/haptic/dummy/*.c) \
	$(wildcard ./src/io/*.c) \
	./src/io/generic/SDL_asyncio_generic.c \
	$(wildcard ./src/joystick/*.c) \
	$(wildcard ./src/joystick/dummy/*.c) \
	$(wildcard ./src/joystick/morphos/*.c) \
	$(wildcard ./src/joystick/virtual/*.c) \
	$(wildcard ./src/libm/*.c) \
	$(wildcard ./src/loadso/morphos/*.c) \
	$(wildcard ./src/loadso/morphos/libdll/*.c) \
	$(wildcard ./src/locale/*.c) \
	$(wildcard ./src/locale/morphos/*.c) \
	./src/main/generic/SDL_sysmain_callbacks.c \
	./src/main/SDL_main_callbacks.c \
	./src/main/SDL_runapp.c \
	$(wildcard ./src/misc/*.c) \
	$(wildcard ./src/misc/morphos/*.c) \
	$(wildcard ./src/power/*.c) \
	$(wildcard ./src/power/morphos/*.c) \
	$(wildcard ./src/process/*.c) \
	$(wildcard ./src/process/dummy/*.c) \
	$(wildcard ./src/render/*.c) \
	$(wildcard ./src/render/software/*.c) \
	$(wildcard ./src/render/opengl/*.c) \
	$(wildcard ./src/sensor/*.c) \
	$(wildcard ./src/sensor/dummy/*.c) \
	$(wildcard ./src/stdlib/*.c) \
	./src/storage/SDL_storage.c \
	./src/storage/generic/SDL_genericstorage.c \
	$(wildcard ./src/thread/*.c) \
	$(wildcard ./src/thread/pthread/*.c) \
	./src/time/SDL_time.c \
	./src/time/unix/SDL_systime.c \
	$(wildcard ./src/timer/*.c) \
	$(wildcard ./src/timer/morphos/*.c) \
	./src/tray/SDL_tray_utils.c \
	./src/tray/dummy/SDL_tray.c \
	$(wildcard ./src/video/*.c) \
	$(wildcard ./src/video/morphos/*.c) \
	$(wildcard ./src/video/dummy/*.c) \
	$(wildcard ./src/video/yuv2rgb/*.c)

TESTLIB_SOURCES = $(wildcard ./src/test/*.c)

OBJECTS = $(SOURCES:.c=.o)
TESTLIB_OBJECTS = $(TESTLIB_SOURCES:.c=.o)
ALL_OBJECTS = $(OBJECTS) $(TESTLIB_OBJECTS)

all: $(TARGET_STATIC) $(TESTLIB_STATIC)
	@echo All done
	
debug: CFLAGS +=  -D__SDL_DEBUG
debug: all

$(TESTLIB_STATIC): $(TESTLIB_OBJECTS)
	@echo Creating $@
	$(AR) crvs $@ $^
	$(RANLIB) $@

$(TARGET_STATIC): $(OBJECTS)
	@echo Creating $@
	$(AR) crvs $@ $^
	$(RANLIB) $@

clean:
	@echo Cleaning
	@rm -f $(TARGET_STATIC) $(TESTLIB_STATIC) $(ALL_OBJECTS) $(DEPS)

install: all
	mkdir -p /gg/usr/local/lib
	mkdir -p /gg/usr/local/include/SDL3
	cp -f $(TARGET_STATIC) /gg/usr/local/lib
	cp -f $(TESTLIB_STATIC) /gg/usr/local/lib
	cp -f include/SDL3/*.h /gg/usr/local/include/SDL3

%.o : %.c
	@echo Compiling $<
	$(CC) -o $@ -c $< $(CFLAGS)

# ALTIVEC
src/video/SDL_blit_N.o: src/video/SDL_blit_N.c
	$(CC) $(CFLAGS) -fvec -maltivec -faltivec -mabi=altivec -o $@ -c src/video/SDL_blit_N.c

