# Makefile to build the examples

CC     = ppc-morphos-gcc-11
CFLAGS = -O3 -noixemul -DHAVE_OPENGL -Wall -I../include -I../include/build_config -I../src
LIBS   = -noixemul -L.. -lSDL3_test -lSDL3 -lGL -lpthread -lm

SRC_FILES = $(wildcard */*/*.c)
DEPS = $(SRC_FILES:.c=.d)

TARGETS = \
	renderer-clear \
	renderer-primitives \
	renderer-lines \
	renderer-points \
	renderer-rectangles \
	renderer-textures \
	renderer-streaming-textures \
	renderer-rotating-textures \
	renderer-scaling-textures \
	renderer-geometry \
	renderer-color-mods \
	renderer-viewport \
	renderer-cliprect \
	renderer-read-pixels \
	renderer-debug-text \
	renderer-affine-textures \
    asyncio-load-bitmaps \
    audio-simple-playback \
    audio-simple-playback-callback \
    audio-load-wav \
    audio-multiple-streams \
    audio-planar-data \
    demo-snake \
    demo-woodeneye-008 \
    demo-infinite-monkeys \
    demo-bytepusher \
    input-joystick-polling \
    input-joystick-events \
	input-gamepad-polling \
	input-gamepad-events \
	misc-power \
	misc-clipboard
	

all: $(TARGETS)


# renderer
renderer-clear: renderer/01-clear/clear.o
	$(CC) -o $@ $^ $(LIBS)

renderer-primitives: renderer/02-primitives/primitives.o
	$(CC) -o $@ $^ $(LIBS)

renderer-lines: renderer/03-lines/lines.o
	$(CC) -o $@ $^ $(LIBS)

renderer-points: renderer/04-points/points.o
	$(CC) -o $@ $^ $(LIBS)

renderer-rectangles: renderer/05-rectangles/rectangles.o
	$(CC) -o $@ $^ $(LIBS)

renderer-textures: renderer/06-textures/textures.o
	$(CC) -o $@ $^ $(LIBS)

renderer-streaming-textures: renderer/07-streaming-textures/streaming-textures.o
	$(CC) -o $@ $^ $(LIBS)

renderer-rotating-textures: renderer/08-rotating-textures/rotating-textures.o
	$(CC) -o $@ $^ $(LIBS)

renderer-scaling-textures : renderer/09-scaling-textures/scaling-textures.o
	$(CC) -o $@ $^ $(LIBS)

renderer-geometry: renderer/10-geometry/geometry.o
	$(CC) -o $@ $^ $(LIBS)

renderer-color-mods: renderer/11-color-mods/color-mods.o
	$(CC) -o $@ $^ $(LIBS)

renderer-viewport: renderer/14-viewport/viewport.o
	$(CC) -o $@ $^ $(LIBS)

renderer-cliprect: renderer/15-cliprect/cliprect.o
	$(CC) -o $@ $^ $(LIBS)

renderer-read-pixels: renderer/17-read-pixels/read-pixels.o
	$(CC) -o $@ $^ $(LIBS)

renderer-debug-text: renderer/18-debug-text/debug-text.o
	$(CC) -o $@ $^ $(LIBS)

renderer-affine-textures:renderer/19-affine-textures/affine-textures.o
	$(CC) -o $@ $^ $(LIBS)

# asyncio
asyncio-load-bitmaps: asyncio/01-load-bitmaps/load-bitmaps.o
	$(CC) -o $@ $^ $(LIBS)

# audio
audio-simple-playback: audio/01-simple-playback/simple-playback.o
	$(CC) -o $@ $^ $(LIBS)

audio-simple-playback-callback: audio/02-simple-playback-callback/simple-playback-callback.o
	$(CC) -o $@ $^ $(LIBS)

audio-load-wav: audio/03-load-wav/load-wav.o
	$(CC) -o $@ $^ $(LIBS)

audio-multiple-streams: audio/04-multiple-streams/multiple-streams.o
	$(CC) -o $@ $^ $(LIBS)

audio-planar-data: audio/05-planar-data/planar-data.o
	$(CC) -o $@ $^ $(LIBS)

# demo
demo-snake: demo/01-snake/snake.o
	$(CC) -o $@ $^ $(LIBS)

demo-woodeneye-008: demo/02-woodeneye-008/woodeneye-008.o
	$(CC) -o $@ $^ $(LIBS)

demo-infinite-monkeys: demo/03-infinite-monkeys/infinite-monkeys.o
	$(CC) -o $@ $^ $(LIBS)

demo-bytepusher: demo/04-bytepusher/bytepusher.o
	$(CC) -o $@ $^ $(LIBS)

# input
input-joystick-polling: input/01-joystick-polling/joystick-polling.o
	$(CC) -o $@ $^ $(LIBS)

input-joystick-events: input/02-joystick-events/joystick-events.o
	$(CC) -o $@ $^ $(LIBS)

input-gamepad-polling: input/03-gamepad-polling/gamepad-polling.o
	$(CC) -o $@ $^ $(LIBS)

input-gamepad-events: input/04-gamepad-events/gamepad-events.o
	$(CC) -o $@ $^ $(LIBS)

# misc
misc-power: misc/01-power/power.o
	$(CC) -o $@ $^ $(LIBS)

misc-clipboard: misc/02-clipboard/clipboard.o
	$(CC) -o $@ $^ $(LIBS)

clean:
	rm -f $(TARGETS) */*/*.o $(DEPS)

%.d : %.c
	@echo Making dependencies for $<
	@$(CC) -MM -MP -MT $(@:.d=.o) -o $@ $< $(CFLAGS)

%.o : %.c
	@echo Compiling $<
	@$(CC) -o $@ -c $< $(CFLAGS)

# Load .d files
ifneq ($(MAKECMDGOALS),clean)
-include $(DEPS)
endif
