#!/usr/bin/perl
#
# gen_morphos_glue.pl - generated by AI - big help :-)
#
# Generate the MorphOS shared-library (sdl3.library) glue from the canonical
# public API list in src/dynapi/SDL_dynapi_procs.h.
#
# Outputs (all overwritten):
#   src/core/morphos/SDL_stubs.h            - STUB() list -> LVO trampolines + FuncTable pointers
#   src/core/morphos/sdk/fd/sdl3_lib.fd     - function descriptor file (cvinclude.pl input)
#   src/core/morphos/sdk/clib/sdl3_protos.h - C prototypes (cvinclude.pl input, #if 0 for the compiler)
#
# The ORDER of the entries is ABI law: it is identical in the .fd and in
# SDL_stubs.h, both produced in a single pass, so LVO -30 in a client always
# lands on the matching LIB_ trampoline in the library.
#
# Regenerate after every SDL update, then rebuild the .fd-derived headers:
#   perl build-scripts/gen_morphos_glue.pl
#   make -f Makefile.mos headers
#
# This software is provided 'as-is', without any express or implied warranty.

use strict;
use warnings;

my $root = shift @ARGV;
if (!defined $root) {
    # default: repo root relative to this script (build-scripts/..)
    ($root = $0) =~ s![\\/]build-scripts[\\/][^\\/]+$!!;
    $root = '.' if $root eq $0 || $root eq '';
}

my $procs = "$root/src/dynapi/SDL_dynapi_procs.h";
my $out_stubs  = "$root/src/core/morphos/SDL_stubs.h";
my $out_fd     = "$root/src/core/morphos/sdk/fd/sdl3_lib.fd";
my $out_protos = "$root/src/core/morphos/sdk/clib/sdl3_protos.h";

open(my $in, '<', $procs) or die "Cannot open $procs: $!\n";

my @entries;      # [ rc, fn, params, args, ret ]
my %seen;
my $in_varargs = 0;

# Functions that <SDL3/SDL.h> hard-aliases to the libc equivalent for every
# build (SDL_stdinc.h, guarded only by SDL_SLOW_MEMCPY).  Giving them an LVO
# would make the generated ppcinline macro fight that alias ("SDL_memcpy
# redefined") and, worse, route memcpy through the jump table.  Keep them
# out of the library ABI entirely - callers just get memcpy/memmove/memset.
my %exclude = map { $_ => 1 } qw(
    SDL_memcpy
    SDL_memmove
    SDL_memset
);

# MorphOS-private glue LVOs that are NOT in src/dynapi/SDL_dynapi_procs.h.
# They are appended AFTER every generated entry so no existing LVO offset ever
# moves. Each needs:
#   - an .fd line (custom calling convention allowed)
#   - a real C prototype in sdl3_protos.h (BEFORE the "#if 0", so the compiler
#     that builds the client glue can see it)
#   - a hand-written LIB_xxx in src/core/morphos/SDL_startup.c
#   - a hand-added (APTR)&LIB_xxx in the FuncTable[] of src/core/morphos/SDL_library.c
# They are deliberately NOT emitted into SDL_stubs.h (no generated trampoline).
my @manual_lvos = (
    {
        fd    => 'SDL_InitTGL(glcptr,tglptr)(base,sysv)',
        proto => 'void SDL_InitTGL(void **glcptr, struct Library **tglptr)',
    },
);

while (my $line = <$in>) {
    chomp $line;

    if ($line =~ /^\s*#\s*ifndef\s+SDL_DYNAPI_PROC_NO_VARARGS/) { $in_varargs = 1; next; }
    if ($in_varargs && $line =~ /^\s*#\s*endif/)               { $in_varargs = 0; next; }
    next if $in_varargs;

    next unless $line =~ /^\s*SDL_DYNAPI_PROC\s*\((.*)\)\s*$/;
    my $body = $1;

    # split $body on top-level commas (depth-aware; handles params/args parens)
    my @f;
    my $depth = 0;
    my $cur = '';
    for my $ch (split //, $body) {
        if    ($ch eq '(') { $depth++; $cur .= $ch; }
        elsif ($ch eq ')') { $depth--; $cur .= $ch; }
        elsif ($ch eq ',' && $depth == 0) { push @f, $cur; $cur = ''; }
        else  { $cur .= $ch; }
    }
    push @f, $cur;

    die "Bad SDL_DYNAPI_PROC line (got ".scalar(@f)." fields): $line\n" unless @f == 5;

    my ($rc, $fn, $params, $args, $ret) = map { my $s = $_; $s =~ s/^\s+//; $s =~ s/\s+$//; $s } @f;

    next unless $fn =~ /^SDL_/;          # drop JNI_OnLoad etc.
    next if $exclude{$fn};               # libc-aliased, see %exclude above
    if ($seen{$fn}++) { warn "duplicate symbol skipped: $fn\n"; next; }

    push @entries, [ $rc, $fn, $params, $args, $ret ];
}
close $in;

my $count = scalar @entries;
die "Parsed 0 entries - wrong input?\n" unless $count;

my $year = 1900 + (localtime)[5];
my $banner = <<"EOT";
/*
  Simple DirectMedia Layer
  Copyright (C) 1997-$year Sam Lantinga <slouken\@libsdl.org>

  This software is provided 'as-is', without any express or implied warranty.
*/
EOT

# ---------------------------------------------------------------- SDL_stubs.h
{
    open(my $o, '>', $out_stubs) or die "Cannot write $out_stubs: $!\n";
    print $o $banner;
    print $o <<'EOT';

/* DO NOT EDIT - generated by build-scripts/gen_morphos_glue.pl
 *
 * Included three ways:
 *   GENERATE_STUBS    -> __saveds LVO trampolines (compiled into sdl3.library)
 *   GENERATE_POINTERS -> comma list of &LIB_xxx for the library FuncTable[]
 *   (neither)         -> forward declarations of LIB_xxx
 *
 * The trampoline body deliberately calls the real SDL_xxx with a K&R
 * (unprototyped) declaration so the compiler forwards r3-r10 / f1-f13
 * untouched and 64-bit / FP return values in r3:r4 / f1 survive the
 * r13 reload performed by __saveds.
 */

#undef STUB

#if defined(GENERATE_STUBS)
#define STUB(name) extern int name(); int __saveds LIB_##name() { return name(); }
#elif defined(GENERATE_POINTERS)
#define STUB(name) (APTR)&LIB_##name ,
#else
#define STUB(name) extern int LIB_##name();
#endif

EOT
    print $o "\t/* $count public entries - order is ABI law, must match sdl3_lib.fd */\n";
    for my $e (@entries) {
        print $o "\tSTUB($e->[1])\n";
    }
    close $o;
}

# ---------------------------------------------------------------- sdl3_lib.fd
{
    open(my $o, '>', $out_fd) or die "Cannot write $out_fd: $!\n";
    print $o "##base _SDL3Base\n";
    print $o "##bias 30\n";
    print $o "* sdl3.library function descriptors - generated by build-scripts/gen_morphos_glue.pl\n";
    print $o "* NEVER REARRANGE. Order is ABI law and matches src/core/morphos/SDL_stubs.h.\n";
    print $o "* New symbols are appended at the end only.\n";
    print $o "##public\n";
    for my $e (@entries) {
        my $args = $e->[3];
        $args =~ s/^\(//; $args =~ s/\)$//;
        $args =~ s/\s+//g;
        print $o "$e->[1]($args)(sysv,r12base)\n";
    }
    print $o "* --- MorphOS-private glue LVOs (keep LAST; hand-wired in SDL_library.c) ---\n";
    print $o "$_->{fd}\n" for @manual_lvos;
    close $o;
}

# ------------------------------------------------------------- sdl3_protos.h
{
    open(my $o, '>', $out_protos) or die "Cannot write $out_protos: $!\n";
    print $o "#ifndef CLIB_SDL3_PROTOS_H\n#define CLIB_SDL3_PROTOS_H\n\n";
    print $o $banner;
    print $o <<'EOT';

/* DO NOT EDIT - generated by build-scripts/gen_morphos_glue.pl
 *
 * Real prototypes for every LVO in sdl3_lib.fd. cvinclude.pl parses this file
 * for the argument types; the C compiler skips it (the bodies are #if 0) and
 * takes the prototypes from <SDL3/SDL.h> instead.
 */

#ifndef SDL_h_
#include <SDL3/SDL.h>
#endif

EOT
    # MorphOS-private glue prototypes - REAL (outside the "#if 0"): the client
    # glue in src/core/morphos/devenv/ is compiled against these.
    print $o "struct Library;\n";
    print $o "$_->{proto};\n" for @manual_lvos;
    print $o "\n#if 0\n";
    for my $e (@entries) {
        my ($rc, $fn, $params) = @{$e}[0,1,2];
        # strip SAL-ish annotation macros cvinclude does not know
        for ($params) {
            s/SDL_(IN|OUT|INOUT)_[A-Z_]*CAP\s*\([^)]*\)\s*//g;
            s/SDL_(PRINTF|SCANF|WPRINTF)_[A-Z_]*STRING\s*//g;
            s/SDL_ANALYZER_NORETURN\s*//g;
            s/\s+/ /g;
            s/\(\s+/(/; s/\s+\)/)/;
        }
        print $o "$rc $fn$params;\n";
    }
    print $o "#endif\n\n#endif /* CLIB_SDL3_PROTOS_H */\n";
    close $o;
}

print "gen_morphos_glue.pl: $count public functions\n";
print "  -> $out_stubs\n  -> $out_fd\n  -> $out_protos\n";
