# Makefile to build renderbench for MorphOS, from the SDL2 tree

CC      = ppc-morphos-gcc-9
STRIP   = ppc-morphos-strip
CFLAGS  = -noixemul -O2 -Wall -I../../include
LIBS    = -L../../src/core/morphos/devenv/lib/ -lSDL2 -lGL -noixemul -lm

all: renderbench

renderbench: renderbench.c
	$(CC) $(CFLAGS) -o $@.db $< $(LIBS)
	$(STRIP) -o $@ $@.db

clean:
	rm -f renderbench renderbench.db
